### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by vazhnov** [freeDSP/freeDSP-OCTAVIA#1]
Hello!

Thank you for great project!
Could you please add a `LICENSE` file with CC-BY-SA-4.0 license text, the same as in other your projects?
For example:
* https://github.com/freeDSP/freeDSP-CLASSIC-SMD-B
* https://github.com/freeDSP/freeDSP-aurora

**Comment by CyberPit** [comment]
O-kay、Just Added.

**Comment by CyberPit** [comment]
Done.

**Comment by vazhnov** [comment]
Thank you very much!
